awslabs/osml-model-runner

src/aws/osml/model_runner/app.py
src/aws/osml/model_runner/tile_worker/tile_worker_utils.py
test/aws/osml/model_runner/tile_worker/test_tile_worker_utils.py

*Issue #, if available:* n/a
- Update MR to Create Valid SICD Tiles from a Full SICD Image
- Removed `test_create_gdal_translate_kwargs` from test since it's already presented in `osml-imagery-toolkit` 
**Test**
- Ran `npm run integ` and validated that there's no errors / issues
| image type | model type | before (in seconds) | after (in seconds)|
|--|--|--|--|
| small | centerpoint | 1.9766190052032470703125  | 6.119431018829345703125 |
| large | flood | 258.321047306060791015625  | 228.4590361118316650390625 |
| small | aircraft | 4.84906291961669921875 | 3.4929721355438232421875 |
| tile_tif | aircraft | 3.718281269073486328125 | 3.4991703033447265625 |
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

update mr to create valid SICD tiles

---

src/aws/osml/model_runner/tile_worker/tile_worker_utils.py

Fixing a bug where we were swapping coordinates incorrectly in ``tile_worker_utils.py``
*Testing:*
This has been deployed, integration tested, and run against the aircraft model to validate returns are as expected.

fix: fix tile worker coords

---

setup.cfg
test/aws/osml/model_runner/inference/test_feature_utils.py

This change pulls in the latest osml-imagery-toolkit release and updates some fragile unit tests that were impacted by the upgrade. 

fix: upate to toolkit-v1.1.1 and fix tests

---

src/aws/osml/model_runner/app.py
src/aws/osml/model_runner/inference/__init__.py
src/aws/osml/model_runner/inference/detector.py
src/aws/osml/model_runner/inference/endpoint_builder.py
src/aws/osml/model_runner/inference/endpoint_factory.py
src/aws/osml/model_runner/inference/http_detector.py
src/aws/osml/model_runner/inference/sm_detector.py
src/aws/osml/model_runner/tile_worker/tile_worker.py
src/aws/osml/model_runner/tile_worker/tile_worker_utils.py
test/aws/osml/model_runner/inference/test_feature_detector_factory.py
test/aws/osml/model_runner/inference/test_sm_detector.py
test/test_app.py

* Added support for model runner to to send inference requests to HTTP endpoints in addition to SageMaker endpoints. Implemented unit test for new classes and updated logic. 
*Testing:*
* Successfully ran tox unit tests 
* Deployed changes with the latest guidance baseline and confirmed integration tests are functional
* Ran various images through the aircraft model to ensure behavior is expected.

feat: support http model endpoints

---

.github/workflows/docker-build.yml
.github/workflows/docker-publish-dockerhub.yml
.github/workflows/docker-publish-github.yml
.github/workflows/documentation-publish.yml
.github/workflows/osml-model-runner-build.yml
.github/workflows/osml-model-runner-publish.yml
.github/workflows/python-publish.yml
.github/workflows/python-tox.yml

- Restructure the workflows. There are 2 workflows:
- osml-model-runner-build 
- This workflow will be executed only IF the pull request have been made to `dev` or `main` branch. 
- osml-model-runner-publish
- This workflow will be executed only IF the changes have been merged into `dev` or `main` branch. This will publish docker container to respective repository (github or dockerhub) and if its on `main` branch, it will published an update to pypi and push documentation pages to `gh-pages` branch
- Eliminate all commits id for github actions and used stable version of it

Update Github action workflows

---

.github/workflows/docker-publish-dockerhub.yml
.github/workflows/osml-model-runner-publish.yml

- Latest github action failed due to the incorrect dockerhub name. It was fetching the entire repo name (org/repo-name) rather than partial repo name (repo-name). 

Update the dockerhub name

---

scripts/run_container.sh

This implements a script to run a local model runner container. It pulls the desired container ENV from. the deployed Fargate task definition.
*Testing:*
Ran container locally and observed functional output.

feat: adding script to run model runner locally

---

src/aws/osml/model_runner/app.py
src/aws/osml/model_runner/common/__init__.py
src/aws/osml/model_runner/common/typing.py
src/aws/osml/model_runner/database/job_table.py
src/aws/osml/model_runner/database/region_request_table.py
src/aws/osml/model_runner/tile_worker/tile_worker_utils.py
test/aws/osml/model_runner/database/test_job_table.py
test/aws/osml/model_runner/database/test_region_request_table.py
test/aws/osml/model_runner/inference/test_feature_utils.py
test/test_app.py

fixing case where status monitor shows success when tiles fail and updating tests

fixing incorrect status on failed tiles

---

src/aws/osml/model_runner/inference/http_detector.py

Fixing a bug that causes the HTTP model endpoint calls to crash due to a property for the NOOP model not existing.

fix: fixing http detector bug

---

setup.cfg

- Update `osml-imagery-toolkit` to v1.2.0
- Update `shapely` version to be greater than 1.8.5 since `osml-imagery-toolkit` set the `shapely` version to 2.0.2

fix: Update osml-imagery-toolkit and shapely version

---

.dockerignore
Dockerfile

Updating the container build process to be more optimal and produce a smaller base image for the model runner package using several techniques found in:
* https://jcristharif.com/conda-docker-tips.html
* https://docs.docker.com/build/building/multi-stage/
This takes the base image produces from the docker build from 3.5GB to 1.86GB in size.
*Testing:*
Deployed and tested changes in my dev account. 

fix: optimize container size

---

.github/workflows/python-tox.yml
src/aws/osml/model_runner/app.py
test/aws/osml/model_runner/database/test_ddb_helper.py
test/aws/osml/model_runner/database/test_endpoint_statistics_table.py
test/aws/osml/model_runner/database/test_feature_table.py
test/aws/osml/model_runner/database/test_job_table.py
test/aws/osml/model_runner/database/test_region_request_table.py
test/aws/osml/model_runner/queue/test_request_queue.py
test/aws/osml/model_runner/status/test_sns_helper.py
test/aws/osml/model_runner/status/test_status_monitor.py
test/test_app.py
tox.ini

* Updating the logic we use to compute the geographic extents of an image for visualization - it still isn't great but it's better and will support a broader range of imagery that is reprocessed orthorectified imagery, if it's non rectangular imagery or non-standard in other ways this bbox based approach isn't going to be flexible enough to be accurate but we can follow up on that later.
* Also updating moto implementation per it's documentation as all the tests broke with it's latest release....
*Testing*
Deployed and tested changes on various image formats in my dev account. Validated the extents are not computed correctly for the imagery that was previously failing.
By submitting this pull request, I confirm that you can use, modify, …

fix: updating extents calculation

---

bin/oversightml-mr-entry-point.py
setup.cfg
src/aws/osml/model_runner/app.py
src/aws/osml/model_runner/common/__init__.py
src/aws/osml/model_runner/common/log_context.py
src/aws/osml/model_runner/status/status_monitor.py
src/aws/osml/model_runner/tile_worker/tile_worker.py
src/aws/osml/model_runner/tile_worker/tile_worker_utils.py
test/aws/osml/model_runner/common/test_log_context.py

These changes update all of the Python logging calls in ModelRunner to output JSON structured log records. Each of these log records will have the job_id and image_id of the request which will allow operators to quickly search for all logs associated with a specific job_id which will aggregate and filter results from across the cluster. These updates also enable more complex analysis and visualization of log records using CloudWatch log insights.
NEW DEPENDENCY: python-json-logger >= 2.0.0

feat: output structured logs with job context

---

bin/oversightml-mr-entry-point.py
src/aws/osml/model_runner/app.py
src/aws/osml/model_runner/app_config.py
src/aws/osml/model_runner/common/metrics_utils.py
src/aws/osml/model_runner/database/feature_table.py
src/aws/osml/model_runner/inference/http_detector.py
src/aws/osml/model_runner/inference/sm_detector.py
src/aws/osml/model_runner/tile_worker/tile_worker.py
src/aws/osml/model_runner/tile_worker/tile_worker_utils.py
test/aws/osml/model_runner/tile_worker/test_tile_worker_utils.py
test/test_app.py

These changes replace the existing CloudWatch metrics generated by ModelRunner with a new set that are more inline with AWS conventions. Key changes include:
- Moving the metrics to the OSML/ModelRunner Namespace to deconflict with other OversightML project metrics.
- Standardized metric names for Duration, Invocations, Errors, Retries, and Throttles
- Use of the Operation dimension to associated metrics with a specific phase of the MR processing. 
- Introduction of the InputFormat and ModelName dimensions to further differentiate metrics for key inputs.
A companion CR including changes to the osml-cdk-constructs will be published to update the dashboard examples. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

feat: new standardized metrics with dimensions

---

.github/workflows/documentation-publish.yml
.github/workflows/python-publish.yml

- The documentation failed due to not supporting Python 3.12, pinning it as Python 3.10
- Update publish workflow not to rely on PyPi tokens

fix: Update Documentation / Publish workflow

---

.github/workflows/notify.yml

- Without the `ref` (optional property), it will default to to whichever branch it got merged in (for example: main) and will try to cut PR against the <name> (in this case: main) branch in guidance repo. Since we do not have `dev` branch anymore, we would need to set the `ref` as `dev` so it can cut PR against the dev branch in guidance repo. 

build(fix): Add ref tag to cut submodule PR to guidance repo

---

README.md
src/aws/osml/model_runner/api/image_request.py
src/aws/osml/model_runner/app.py
src/aws/osml/model_runner/database/job_table.py
src/aws/osml/model_runner/status/image_request_status.py
src/aws/osml/model_runner/status/status_monitor.py
test/aws/osml/model_runner/api/test_image_request.py
test/aws/osml/model_runner/queue/test_request_queue.py
test/aws/osml/model_runner/status/test_image_request_status.py
test/aws/osml/model_runner/status/test_status_monitor.py
test/test_api.py
test/test_app.py
tox.ini

- The "job_arn" parameter is redundant with "job_id" and therefore not needed. This will not break any changes.

fix: deprecate job_arn request parameter

---

src/aws/osml/model_runner/app.py

In this context, a sink is the destination of a data flow (S3, Kinesis, etc.) so sync is incorrect and may cause confusion.

fix: rename sync to sink

---

src/aws/osml/model_runner/tile_worker/__init__.py
src/aws/osml/model_runner/tile_worker/variable_overlap_tiling_strategy.py
test/aws/osml/model_runner/tile_worker/test_variable_overlap_tiling_strategy.py

This PR contains an implementation of the VariableOverlapTilingStrategy that has been requested by some users with CV models who need to receive full tiles of real pixels. This new region and tile decomposition strategy has been implemented using the new TilingStrategy abstraction which will allow us to easily enable this behavior with minimal code changes.
**Figure 1:** An example 25Kx12K image with 4096 tiles, a minimum of 100 pixel overlap and a 10K region size divided into regions using the baseline tiling strategy (VariableTileTilingStrategy). Note that the region size and overlap are fixed at the requested values but that tiles at the edges of each region and the image are truncated.
**Figure 2:** The same example image divided into regions using the new …

feat: add variable overlap tiling strategy

---

src/aws/osml/model_runner/inference/feature_selection.py
test/aws/osml/model_runner/inference/test_feature_selection.py

This change avoids errors in the feature selection processing triggered by features that have a zero area bounding box. Those cases can happen for ML detections reported as a single point or for detections that were erroneously reported with a zero width or height bounding box. 
This problem originally manifested as a divide by zero error in the feature selection normalization process but if that is fixed directly it exposed other error paths through the 3rd party ensemble-boxes library. Instead of working around each of those issues independently it was more robust to enforce the non-zero area assumption made by this code by adding a small (0.1 pixel) buffer to the bbox width or height if it is zero. This allows point features to flow through the normal feature selection process along …

fix: feature selection error for zero area features

---

src/aws/osml/model_runner/app_config.py
src/aws/osml/model_runner/sink/kinesis_sink.py
test/aws/osml/model_runner/sink/test_kinesis_sink.py

This pull request enhances the KinesisSink class by updating the `_flush_stream` method to improve the handling of records sent to the Kinesis stream. The changes ensure compliance with Kinesis limits, specifically allowing a maximum of 500 records per request, while the total request size does not exceed 5 MB.
**Ran the load test for an hour:**
| Metric                       | Before PR               | This PR               |
|------------------------------|-------------------------|-------------------------|
| Total Images Sent            | 112                     | 115                     |
| Total Images In-Progress     | 14                      | 2                       |
| Total Images Processed       | 98                      | 113 …

fix: use put_records for kinesis due to rate exceeded

---

src/aws/osml/model_runner/app_config.py
src/aws/osml/model_runner/inference/http_detector.py
src/aws/osml/model_runner/inference/sm_detector.py
src/aws/osml/model_runner/tile_worker/tile_worker.py
test/aws/osml/model_runner/inference/test_feature_utils.py
test/aws/osml/model_runner/inference/test_sm_detector.py
test/aws/osml/model_runner/status/test_image_status_monitor.py
test/aws/osml/model_runner/status/test_region_status_monitor.py
test/configuration.py
test/test_app.py

This PR replaces the real `find_features` method of the `SMDetector` class with a mocked version of (`invoke_endpoint`) called by the SageMaker client during testing, simulating a GeoJSON response from a SageMaker model without real endpoint invocations. Removing any logic for supporting NOOP models in the find features methods in the associated Detection classes.
1. **Mocking `find_features`:**
- Added `mock_find_features` to simulate model inference, returning a GeoJSON `FeatureCollection`.
- Patched `find_features` in `SMDetector` using `unittest.mock.patch.object` to use the mock in tests.
2. **Updated Unit Test (`test_process_bounds_image_request`):**
- Integrated `mock_find_features` into the `SMDetector` instance for controlled testing.
- Retained …

fix: remove noop model logic

---

src/aws/osml/model_runner/app.py
src/aws/osml/model_runner/region_request_handler.py
test/aws/osml/model_runner/test_reqion_request_handler.py
test/test_app.py

This PR introduces refactoring of the `RegionRequestHandler` class to decouple region processing logic from `ModelRunner`. The `RegionRequestHandler` now makes it the region processing logic self-contained, modular, and easier to test. Additionally, changes to the `ModelRunner` class were made to initialize this handler with the appropriate dependencies.
Unit tests were also updated to split out region processing testing associated with the new class.
1. **Decoupled `RegionRequestHandler` from `ModelRunner`:**
- `RegionRequestHandler` now takes in its own initialization parameters:
- `region_request_table`, `job_table`, `region_status_monitor`, `endpoint_statistics_table`
- `tiling_strategy`, `region_request_queue`, `endpoint_utils`, `config`
- This …

refactor: break out RegionRequestHandler class from app.py

---

src/aws/osml/model_runner/api/image_request.py
src/aws/osml/model_runner/app.py
src/aws/osml/model_runner/database/job_table.py
src/aws/osml/model_runner/image_request_handler.py
src/aws/osml/model_runner/region_request_handler.py
test/aws/osml/model_runner/test_image_request_handler.py
test/aws/osml/model_runner/test_reqion_request_handler.py
test/test_app.py

This PR introduces refactoring of the `ImageRequestHandler` class to decouple region processing logic from `ModelRunner`. The `ImageRequestHandler` now makes it the image processing logic self-contained, modular, and easier to test. Additionally, changes to the `ModelRunner` class were made to initialize this handler with the appropriate dependencies. Methods were refined in the `ImageRequestHandler` class to make them more compact and testable.
Unit tests were updated to split out region processing testing associated with the new class. 
Additional method was added to the `JobItem` dataclass which allows conversion to from an `ImageRequest` to a `JobItem`.
By submitting this pull …

refactor: implement ImageRequestHandler class 

---

src/aws/osml/model_runner/inference/feature_utils.py
test/aws/osml/model_runner/inference/test_feature_utils.py

This PR improves the robustness of the `features_to_image_shapes` function by allowing it to handle mixed valid and invalid features without terminating. Additionally, it expands the test coverage to ensure more thorough testing of edge cases and potential failure points in the feature conversion process. 
1. **Enhancement of `features_to_image_shapes`:**
- Updated the function to skip invalid features instead of raising a `ValueError`. This allows the processing of mixed datasets, where valid features can still be converted even if some are malformed or unsupported.
- Added logging to inform users when a feature is skipped due to errors, improving traceability and debugging.
2. **New and Updated Unit Tests:**
- **Refactored …

fix: improving feature util test coverage

---

test/aws/osml/model_runner/status/test_sns_helper.py

Enhanced the `TestSnsHelper` unit tests structure and comments to improve readability, consistency, and understanding. Added detailed comments to each test case and cleaned up the setup and teardown methods.
1. **General Code Cleanup**:
- Reformatted the code for better readability and consistent spacing.
- Ensured line breaks between sections and methods to separate logic clearly.
2. **Added Docstrings and Comments**:
- Provided comprehensive docstrings for each test method, describing the purpose of the test and expected outcomes.
- Added inline comments to clarify specific lines of code, such as explaining mock configurations and base64 encoding.
- Included setup explanations to outline the mock AWS environment preparation, including SNS topic and SQS …

chore: adding comments to test_sns_helper.py

---

.coveragerc
setup.cfg
src/aws/osml/model_runner/common/__init__.py
src/aws/osml/model_runner/common/ensemble_boxes_nms.py
src/aws/osml/model_runner/inference/feature_selection.py
test/aws/osml/model_runner/common/test_ensemble_boxes_nms.py

This file contains code for performing non-maximum suppression (NMS) on bounding boxes obtained from multiple object detection models. The code was originally taken from the following GitHub repository:
https://github.com/ZFTurbo/Weighted-Boxes-Fusion/blob/master/ensemble_boxes/ensemble_boxes_nms.py
The original author is 'ZFTurbo' (https://kaggle.com/zfturbo).
This implementation provides functions for standard NMS, linear soft-NMS, and gaussian soft-NMS. It also includes a method for preparing the boxes, scores, and labels before applying NMS.
Along with some motification to match the conventional OSML styles such as typings and docstrings. 
By submitting this pull request, I …

refactor: copy ensemble_boxes_nms from ensemble_boxes package

---

.github/workflows/tox.yml
src/aws/osml/model_runner/model_runner.py
src/aws/osml/model_runner/scheduler/__init__.py
src/aws/osml/model_runner/scheduler/fifo_image_scheduler.py
src/aws/osml/model_runner/scheduler/image_scheduler.py
test/aws/osml/model_runner/scheduler/test_fifo_image_scheduler.py
test/aws/osml/model_runner/test_model_runner.py
tox.ini

This change introduces an abstraction for an ImageScheduler that is responsible for selecting the next image to process from a collection of pending requests. Instead of reading directly from the image request queue the ModelRunner loops will ask the ImageScheduler for the next image whenever there are no regions to process. The current code has been refactored as a first-in-first-out (FIFO) scheduler which will let us maintain the current behavior using the new abstraction. Future PRs will introduce new scheduling options based on lessons learned from the ongoing load testing.
New unit tests were added to verify behavior of the FIFO scheduler and the ModelRunner updates. In addition these updates were deployed into a development account and integration test images were run to confirm …

refactor: add image scheduler abstraction

---

src/aws/osml/model_runner/database/__init__.py
src/aws/osml/model_runner/database/dataclass_ddb_mixin.py
src/aws/osml/model_runner/database/requested_jobs_table.py
test/aws/osml/model_runner/database/test_dataclass_ddb_mixin.py
test/aws/osml/model_runner/database/test_requested_jobs_table.py

This change adds a new job status table to the ModelRunner database module. This table will be used by a future load based scheduler as temporary storage for image processing jobs that have been pulled from the SQS queue but are not completed. 
Note that this table is implemented using different DDB utilities than our other tables. Instead of using the DDBHelper this class interacts with the boto3 DynamoDB table resource directly. The intent was to provide more robust encapsulation for behaviors like conditional updates and table scans. Generalizing those operations to a helper class risks unexpected side effects if those utilities are updated when tuning future tables. Each row is implemented as a dataclass (ImageRequestStatusRecord) but the reusable logic of converting dataclasses …

feat: add requested jobs table

---

src/aws/osml/model_runner/queue/__init__.py
src/aws/osml/model_runner/queue/buffered_image_request_queue.py
src/aws/osml/model_runner/scheduler/__init__.py
src/aws/osml/model_runner/scheduler/endpoint_load_image_scheduler.py
test/aws/osml/model_runner/queue/test_buffered_image_request_queue.py
test/aws/osml/model_runner/scheduler/test_endpoint_load_image_scheduler.py

This change adds a new endpoint load scheduler to ModelRunner but it does not enable the feature in the application.
The EndpointLoadImageScheduler is a job scheduler that picks an image processing job that will drive requests to the least utilized model endpoint. It estimates an endpoint's utilization as the ratio of incomplete image regions for all jobs sending tiles to that endpoint to the number of instances currently allocated to the endpoint.
That scheduler depends on a new BufferedImageRequestQueue class which is a SQS queue that uses a RequestedJobsTable to provide a look ahead of some number of jobs. This queue mimics regular SQS features like retry visibility timeout and a max retry limit for the jobs and will automatically move problematic or expired requests to the DLQ.
Unit …

feat: add endpoint load scheduler

---

src/aws/osml/model_runner/database/dataclass_ddb_mixin.py
src/aws/osml/model_runner/queue/buffered_image_request_queue.py
test/aws/osml/model_runner/database/test_dataclass_ddb_mixin.py

This change expands the DataclassDDBMixin to support dataclasses that have nested dataclass fields. The previous implementation only supported native types which is a limitation that became apparent when integrating the requested_jobs_table in with real requests decoded from the image queue.
Unit tests have been updated to test the nested dataclass cases.

feat: ddb dataclass mixin supports nested dataclasses

---

src/aws/osml/model_runner/queue/buffered_image_request_queue.py
src/aws/osml/model_runner/scheduler/endpoint_load_image_scheduler.py
test/aws/osml/model_runner/queue/test_buffered_image_request_queue.py
test/aws/osml/model_runner/scheduler/test_endpoint_load_image_scheduler.py

These changes fixes a problem found with the scheduler discovered during integration testing. The buffered queue was incorrectly filtering requests as soon as the number of attempts matched the max number of attempts. If a customer ran without retries that would cause results to be moved to the DLQ as soon as they had started giving no time for the actual job to complete. During this debugging it was also noted that the metrics for the number of requests visible on the queue were not being emitted because they were being written directly to CloudWatch (which is an action MR does not have permissions for) instead of being emitted as embedded metrics to the log stream. 
Both of those problems have been fixed by the changes in this PR and the unit tests were updated to better exercise the …

fix: incorrect purge of in-progress image jobs

---

.coveragerc
src/aws/osml/model_runner/common/ensemble_boxes_nms.py
src/aws/osml/model_runner/inference/feature_selection.py
test/aws/osml/model_runner/common/test_ensemble_boxes_nms.py

Previously, the NMS function would return lists of normalized bounding boxes, scores, and categories which had to be matched to their input features using a hash of the data values.  In some cases this led to collisions where features were not being mapped correctly.  This change alters the return value of the NMS function to include the indexes of the features  so they can be selected without ambiguity.  This also updates the data types to more consistently leverage np arrays and reduce the number of conversions between them and python Lists.

fix: changed NMS to select features based on index position instead of a hash-based lookup
