awslabs/osml-model-runner

- Dockerfile
- setup.cfg
- tox.ini
https://github.com/aws-solutions-library-samples/osml-model-runner/issues/6
Updating import of osml-imagery-toolkit to pull from PyPi instead of a local dependency.  Updating the Dockerfile accordingly. Also taking the action of updating the links in the python configuration to reflect correctly in PyPi repo..
*Testing*
```
tox
python3 -m pip install . 
docker build . -t osml-model-runner:latest
```
> Updating model runner to import imagery-tookit from PyPi

- .github/workflows/python-publish.yml
Creating python publishing automation for this package via Github actions.
> Adding python-publish.yml

- .github/workflows/docker-build.yml
- .github/workflows/docker-publish.yml
Adding docker publishing workflow
> Adding docker publishing workflow

- .github/workflows/documentation.yaml
*Issue #, if available:* N/A
*Description of changes:* Adding a workflow for publishing sphinx documentation. 
> Add workflow for hosting sphinx documentation

- .github/workflows/docker-publish-dockerhub.yml
- Dockerfile
Fixing bug in Dockerfile build due to recent context change. Updating the docker build to use git-lfs.
> Updating Dockerfile

- .github/workflows/documentation.yaml
- .github/workflows/python-tox.yml
Enabling the tox build / test actions for the dev branch. Also fixing the docs publishing action to leverage tox as done in other repos.
> feature: enable dev actions

- setup.cfg
Bumping dev branch to latest release.
> feature: bumping package to v1.1.0

- setup.cfg
Adding requests dependency to package to solve problem with nodes starting from last patch.
> fix: adding requests dep

- .github/workflows/notify-guidance-repo.yml
- .github/workflows/osml-model-runner-publish.yml
- Created a workflow such that it will notify the guidance repo to pull in the new changes from this repository
> Notify guidance repo for updates

- .pre-commit-config.yaml
- pyproject.toml
- src/aws/osml/model_runner/app.py
- src/aws/osml/model_runner/app_config.py
- src/aws/osml/model_runner/database/ddb_helper.py
- src/aws/osml/model_runner/database/exceptions.py
- src/aws/osml/model_runner/database/feature_table.py
- src/aws/osml/model_runner/tile_worker/tile_worker_utils.py
- test/aws/osml/model_runner/database/test_feature_table.py
Update ddb helper to use batch write when writing to the feature table. More notes on testing and validating to come.
> fix: update ddb helper to use batch write

- Dockerfile
- environment-py310.yml
- environment-py311.yml
- setup.cfg
Updating package dependencies to latest-greatest versions.
*Testing*
Deployed and tested changes in dev account.
> fix: updating deps

- setup.cfg
- Bumping configuration version.
> fix: bumping up version

- src/aws/osml/model_runner/api/image_request.py
- src/aws/osml/model_runner/app.py
- src/aws/osml/model_runner/database/feature_table.py
- src/aws/osml/model_runner/database/region_request_table.py
- src/aws/osml/model_runner/inference/feature_utils.py
- src/aws/osml/model_runner/inference/http_detector.py
- src/aws/osml/model_runner/inference/sm_detector.py
- src/aws/osml/model_runner/queue/request_queue.py
- src/aws/osml/model_runner/sink/kinesis_sink.py
- src/aws/osml/model_runner/sink/s3_sink.py
- src/aws/osml/model_runner/status/status_monitor.py
- src/aws/osml/model_runner/tile_worker/tile_worker.py
- src/aws/osml/model_runner/tile_worker/tile_worker_utils.py
moving from .format() to f-strings for consistency.
> refactor: moving from .format() to f-strings

- .github/workflows/pypi.yml
- The removal of the `if` statement from the PyPI workflow was prompted by its dependency on the `workflow_call`, a function exclusively triggered by the release event action.
> build: remove if statement for pypi

- setup.cfg
- Version bump to v2.1.1 to reflect on the below changes
* build(fix): Add ref tag to cut submodule PR to guidance repo by @RanbirAulakh in https://github.com/aws-solutions-library-samples/osml-model-runner/pull/76
* fix: remove broken classification property from sourceMetadata by @edparris in https://github.com/aws-solutions-library-samples/osml-model-runner/pull/78
> build: version update to v2.1.1

- .gitignore
Updating the ``.gitignore`` file to make it easier to understand and update.
> chore: updating .gitignore file

- src/aws/osml/model_runner/sink/s3_sink.py
- test/aws/osml/model_runner/sink/test_s3_sink.py
- There is a potential issue where uploading very large imagery could result in a detection objects file exceeding 5 GB. Therefore, uploading geojson greater than 5 GB may fail. Switching from `s3.put_object` to `s3.upload_file` can resolve this issue. I have confirmed that multipart upload is being used, as indicated by the DEBUG logging.
>  "Event request-created.s3.CreateMultipartUpload: calling handler <function signal_transferring at 0x7f9aa3e6d940>"
> "Submitting task CreateMultipartUploadTask(transfer_id=0, {'bucket': '****, 'key': 'test-d9d3d3869d6cc5bf380288249401cd17/d9d3d3869d6cc5bf380288249401cd17.geojson', 'extra_args': {'ACL': 'bucket-owner-full-control'}}) to executor <s3transfer.futures.BoundedExecutor object at 0x7f9a98a853d0> for transfer …
> fix: change put_object to upload_file to improve performance

- setup.cfg
Bumping version in ``setup.cfg`` to update to v2.2.0 for release.
> build: version update to v2.2.0

- src/aws/osml/model_runner/app.py
- src/aws/osml/model_runner/database/job_table.py
- src/aws/osml/model_runner/tile_worker/__init__.py
- src/aws/osml/model_runner/tile_worker/tile_worker_utils.py
- src/aws/osml/model_runner/tile_worker/tiling_strategy.py
- src/aws/osml/model_runner/tile_worker/variable_tile_tiling_strategy.py
- test/aws/osml/model_runner/tile_worker/test_tile_worker_utils.py
- test/aws/osml/model_runner/tile_worker/test_tiling_strategy.py
- test/aws/osml/model_runner/tile_worker/test_variable_tile_tiling_strategy.py
This code encapsulates the ModelRunner tiling logic inside a new TilingStrategy abstraction. The baseline implementation has been packaged inside VariableTileTilingStrategy and integrated into the ModelRunner class defined in app.py. There should be no functional differences introduced with this PR and the current suite of integration tests have been run successfully without update. This change sets the stage for future updates to the tiling strategy to deliver fixed tile sizes to the model endpoints.
> refactor: tiling strategy refactor

- src/aws/osml/model_runner/database/feature_table.py
This pull request introduces optimizations to the FeatureSelection stage of the OversightML Model Runner, with the goal of improving the overall performance and throughput of the image processing pipeline.
- Optimized the `FeatureTable.get_features()` function to reduce the computational complexity and memory footprint of the feature extraction process.
- Adjusted the default `max_workers` configuration to 10, based on the findings from the load test analysis.
| Metric                  | Before PR, max_workers=5 | After PR, max_workers=5 | After PR, max_workers=16 | After PR, max_workers=10 |
| ----------------------- | ----------------------- | ---------------------- | ----------------------- | ----------------------- |
| Total Images Sent       | 115 …
> fix: refactor featureselection tuneup

- src/aws/osml/model_runner/sink/kinesis_sink.py
- test/aws/osml/model_runner/sink/test_kinesis_sink.py
- Passing incorrect variable typings into the FeatureCollection, it should have been passing a list rather than a Feature according to the typings of FeatureCollection. 
> fix: add missing List in FeatureCollection dump calls

- src/aws/osml/model_runner/database/feature_table.py
- test/aws/osml/model_runner/database/test_ddb_helper.py
- test/aws/osml/model_runner/database/test_endpoint_statistics_table.py
- test/aws/osml/model_runner/database/test_feature_table.py
- test/aws/osml/model_runner/database/test_job_table.py
- test/aws/osml/model_runner/database/test_region_request_table.py
This PR introduces a series of enhancements and new unit tests for various classes interacting with AWS DynamoDB tables. The goal is to increase code coverage, improve robustness, and ensure consistent error handling across all components. Below is a detailed breakdown of the changes and additions:
- **Expanded Test Coverage**:
- Added tests to cover methods for `put_ddb_item`, `get_ddb_item`, `delete_ddb_item`, `update_ddb_item`, and `batch_write_items`.
- Introduced exception tests to validate error handling and resilience under failure scenarios.
- Added checks to verify correct behavior when using conditional expressions and update parameters.
- **Enhanced Assertions**:
- Ensured that test cases validate HTTP response status codes and DynamoDB item …
> chore: update database tests

- test/aws/osml/model_runner/tile_worker/test_tile_worker_utils.py
This PR enhances the unit test coverage for the `tile_worker_utils` module, specifically targeting the `setup_tile_workers`, `process_tiles`, and utility functions. The changes include additional test cases, improved mocking, and detailed comments to clarify the purpose of each test.
1. **Enhanced Test Coverage**:
- **`test_setup_tile_workers`**: 
- Validates the setup process for tile workers, ensuring the correct number of workers is created and started based on `ServiceConfig`.
- Improved assertions to check that each worker is properly started.
- **`test_setup_tile_workers_exception`**:
- Added test to confirm that exceptions during worker setup are correctly handled, raising a `SetupTileWorkersException`.
- **`test_process_tiles`**:
- Updated to …
> chore: updating test coverage for tile_worker_utils.py

- src/aws/osml/model_runner/sink/kinesis_sink.py
- src/aws/osml/model_runner/sink/s3_sink.py
- src/aws/osml/model_runner/sink/sink_factory.py
- test/aws/osml/model_runner/sink/test_kinesis_sink.py
- test/aws/osml/model_runner/sink/test_s3_sink.py
- test/aws/osml/model_runner/sink/test_sink.py
- test/aws/osml/model_runner/sink/test_sink_factory.py
This PR introduces comprehensive unit tests and enhancements across multiple sink-related classes, including `KinesisSink`, `S3Sink`, `Sink`, and `SinkFactory`. These changes aim to improve test coverage, consistency, and robustness of the sink implementations.
- **Expanded Test Coverage**: Added new test cases to handle:
- Edge cases like empty feature lists.
- Validation failures, oversized record handling, and partial write scenarios.
- Correct behavior when using assumed role credentials.
- **Improved Test Clarity**: Added detailed docstrings to explain test scenarios.
- **Cleaned Up Mocks**: Ensured proper setup and teardown of stubs and mocks.
- **New Test Scenarios**: Introduced tests to cover:
- Handling slashes in `image_id` and validating correct …
> chore: updating test coverage for sink submodule

- test/aws/osml/model_runner/queue/test_request_queue.py
This PR enhances the existing unit tests for the `RequestQueue` class by adding descriptive comments, improving readability, and standardizing the assertion methods. The changes ensure better documentation and clarity on the purpose of each test case, facilitating easier maintenance and understanding for future contributors.
1. **Added Docstrings**:
- Each test method now includes a descriptive docstring explaining the purpose and expected behavior of the test. This helps to clarify the test intent and aids in faster understanding for reviewers and future developers.
2. **Standardized Assertions**:
- Replaced `assert` statements with `self.assert` methods for consistency across the test suite. This approach provides clearer test output and integrates better …
> test: cleaning up structure and comments in test_request_queue.py

- src/aws/osml/model_runner/tile_worker/variable_overlap_tiling_strategy.py
- test/aws/osml/model_runner/tile_worker/test_tiling_strategy.py
- test/aws/osml/model_runner/tile_worker/test_variable_overlap_tiling_strategy.py
- test/aws/osml/model_runner/tile_worker/test_variable_tile_tiling_strategy.py
- Cleaned up and added comments to unit tests for `TestVariableTileTilingStrategy`, `TestVariableOverlapTilingStrategy`, and `TestTilingStrategy` classes.
- Improved code readability, structure, and added detailed descriptions for each test case to clarify their purpose and expected behavior.
**Changes:**
1. **Refactoring:**
- Added descriptive comments across all test cases to explain what each test validates.
- Improved code organization with consistent spacing and formatting for better readability.
- Ensured each section of the code is logically separated and easy to understand.
- Added reST style PyDoc comments to class methods missing them.
2. **Test Clarifications:**
- For `TestVariableTileTilingStrategy` and `TestVariableOverlapTilingStrategy`:
- …
> chore: cleanup tiling strategy comments for classes and tests

- setup.cfg
> build: version update to v2.3.0

- src/aws/osml/model_runner/common/observable_event.py
- test/aws/osml/model_runner/common/test_observable_event.py
This change adds a new ObservableEvent class to ModelRunner's common utilities module. This class can be used to define new events that handlers can subscribe to to receive notifications of updates. A general example of the usage is included in the class documentation. While this is a general utility the driving need is to support adding these kinds of events to our ImageRequestHandler and RegionRequestHandler classes allowing them to notify on job status changes the scheduler needs to be aware of.
Additional unit tests have been added to verify the behavior of this class.
> feat: add observable event utility

- scripts/image_converter.py
- src/aws/osml/model_runner/image_request_handler.py
- src/aws/osml/model_runner/inference/feature_utils.py
- src/aws/osml/model_runner/queue/request_queue.py
- src/aws/osml/model_runner/region_request_handler.py
- src/aws/osml/model_runner/sink/kinesis_sink.py
- src/aws/osml/model_runner/sink/s3_sink.py
- src/aws/osml/model_runner/sink/sink_factory.py
- src/aws/osml/model_runner/status/image_status_monitor.py
- src/aws/osml/model_runner/status/region_status_monitor.py
- src/aws/osml/model_runner/tile_worker/tile_worker.py
This PR removes the usage of the Python root logger from throughout the codebase. This removes all uses of "logging.(info, warning, error, exception)"
> remove usage of Python root logger

- METRICS_AND_DASHBOARDS.md
- README.md
This documentation only update adds information about the endpoint load scheduler and the new related metrics to our readme files.
> docs: update documentation for load based scheduling

- scripts/describe_image.py
- scripts/summarize_image.py
This is a minor update to tell python to interpret the regex patterns as raw strings in 2 utility scripts.
> chore: cleanup regex compile string patterns

- README.md
- src/aws/osml/model_runner/image_request_handler.py
- src/aws/osml/model_runner/model_runner.py
- src/aws/osml/model_runner/region_request_handler.py
This PR implements standardized "timeline event" logging throughout the image and region processing flows. Adds start and completion logs with consistent formatting and metadata to enable better tracing of requests through the system. Ensures logs appear in proper chronological order when filtered.
> feat: add timeline event logging

- Dockerfile
This fix is to resolve build error that popped up recently due to a structural requirement implemented by Conda to have users accept channel agreements - resulting in the following build failure errors:
```
> [build 6/8] RUN conda env create -f environment.yml      && conda clean -afy      && find /opt/conda/ -follow -type f -name '*.a' -delete      && find /opt/conda/ -follow -type f -name '*.pyc' -delete      && find /opt/conda/ -follow -type f -name '*.js.map' -delete:
1.023 CondaToSNonInteractiveError: Terms of Service have not been accepted for the following channels. Please accept or remove them before proceeding:
1.023     • https://repo.anaconda.com/pkgs/main
1.023     • https://repo.anaconda.com/pkgs/r
1.023
1.023 To accept a channel's Terms of …
```
> fix: updating Dockerfile
